FROM docker.io/bitnami/drupal:10.3.6-debian-12-r1

# Install necessary packages for SSL
RUN apt-get update && apt-get install -y \
    openssl \
    && rm -rf /var/lib/apt/lists/*

# Copy SSL certificates into the container
COPY DigiCertGlobalRootCA.crt.pem /etc/ssl/certs/ca-cert.pem

# Set environment variables for Drupal to use SSL
ENV DRUPAL_DB_SSL_CA=/etc/ssl/certs/ca-cert.pem

# Ensure the permissions are correct
RUN chmod 644 /etc/ssl/certs/ca-cert.pem
